### ISSUE TITLE
Support file uploads other than images

### ISSUE THREAD

**Issue by albogdano** [Erudika/scoold-pro#32]

**Comment by couviphi** [comment]
Hi Alex,

I am experiencing the same issue with the Live Pro demo. 

Please find below a step-by-step scenario to reproduce it:

1. create a Question
2. in the description box, try Inserting an Image by clicking the icon 
![image](https://user-images.githubusercontent.com/13632654/90150166-3d080980-dd3a-11ea-91c2-d4a778ba15f7.png)
3. The description box changes and invites me to type in a URL for an image:
![image](https://user-images.githubusercontent.com/13632654/90150109-26fa4900-dd3a-11ea-8f86-ba44d9ce7a4d.png)

The issue is that I would like to be given the choice of typing in a URL or Uploading an image from my hard drive.

My expectation is based on Confluence's behavior when it comes to Insert Files and Images. The Confluence user is prompted with the following dialog:
![image](https://user-images.githubusercontent.com/13632654/90150780-dcc59780-dd3a-11ea-82ff-a9e3af7e924c.png)

Here, you have to imagine an option to select one or more image files from My Computer.

I am fully aware that I could use Drag & Drop as a workaround which is great but it's a bit uncomfortable for users because they would have to open a separate File Manager window to find their image file(s) and then drag and drop the file(s).

Bonus points:
- important: allow user to select multiple images at once, same way as Confluence
- important: add preview of the selected image file inside the Insert dialog, same way as Confluence
- not that important and probably much more difficult/expensive to implement: if the user selects only one image file then add functionality for resizing, recentering and cropping the image file directly in the Import dialog (Confluence cannot do that). This is similar to what Android phone/tablet users can already do before sharing an image they select it from their Photos folder (I don't know about iOS devices, but I feel they can do as much as Android).

The devil is in the details!

I hope this helps.

Cheers,

Philippe

**Comment by albogdano** [comment]
Thanks for the suggestions Philippe! I am aware of the limitations of the text editor and we can do more to improve its usability. Image previews and crop/resize editing are out of the scope of the text editor as those features are implemented either natively by each OS or are part of the native browse dialog window. 

To select and image from the hard drive click the "Attach file" button under the tags selector:
![image](https://user-images.githubusercontent.com/346873/90162618-948b9100-dd9d-11ea-86c5-1b090e967f7b.png)

I've opened a new feature request (#42 ) for allowing multiple files to be uploaded at once.
