### ISSUE TITLE
Issue with /scoold search integrate Slack

### ISSUE THREAD

**Issue by kietvo01314** [Erudika/scoold-pro#52]
When I use /scoold search something 
It appear errors
`failed with the error "operation_timeout"`
I can use /scoold ask and answer but errors with search.
I use para backend with tag latest.
Could you help me to tell the errors from ?

**Comment by albogdano** [comment]
This happens when Scoold doesn't respond to requests coming from Slack in less than 3 seconds. Make sure that your Scoold instance is reachable and responding quickly to Slack. This is not a bug - it's an issue with latency. You should find out what is causing the delay and fix it. Could be a DNS resolution problem or a slow server with not enough resources.
